### ISSUE TITLE
Xfce4-panel doesn't list the plugin

### ISSUE THREAD

**Issue by MrHaroldA** [projecthamster/xfce4-hamster-plugin#1]
Install went fine (after installing -dev dependencies) and the .la and .so are sitting nicely in /usr/local/lib/xfce4/panel/plugins, but aren't picked up by the panel so I can't add them. Restarting the panel didn't help.

What to do next? I want a hamster!

**Comment by aquaherd** [comment]
It means it is not fixable here in the plug-in.
