### ISSUE TITLE
Resume a past activity

### ISSUE THREAD

**Issue by MrHaroldA** [projecthamster/xfce4-hamster-plugin#15]
I often resume an activity I stopped a day before, so it would be nice if the popup could show a couple of activities (configurable: 0+) from the past.

**Comment by invidian** [comment]
I think this is already implemented? There is a green arrow, which allows you to start again the same activity?

**Comment by MrHaroldA** [comment]
Well, I don't know anymore ;)

It's has been 7 years since I posted this request, I'm closing it ...
