### ISSUE TITLE
Tags?

### ISSUE THREAD

**Issue by fauno** [projecthamster/xfce4-hamster-plugin#27]
I really like to see the current activity and time passed on my xfce4-panel but I'm missing the possibility to add tags, any plans to add them? Now I have to edit the activity and add them separately.

PS: Is there a way to add/remove panel elements from cli?

**Comment by aquaherd** [comment]
The panel plugin will pass the string you entered verbatim, e.g.:

- 14:00 work@home
- work@work#ProjectM

[timespec ]activity[@category][#tag1][#tag2][...]

I don't know if there is one but the xfce4-panel sources indicate that it would be possible to write a command line remote add/remove app; however a specific location seems not possible via API.

**Comment by fauno** [comment]
cool, thanks!
-- 
http://endefensadelsl.org

**Comment by fauno** [comment]
hi, just tested this with code from master branch and it doesn't work, it takes the #tag as part of the category, so "activity@category#tag" turns into "activity" in category "category#tag"

**Comment by aquaherd** [comment]
Strange, that used to work. Will see if I can fix it.

**Comment by GeraldJansen** [comment]
With a space before # it works.

**Comment by aquaherd** [comment]
Thanks that’s a great find.

**Comment by aquaherd** [comment]
Closing this now
