### ISSUE TITLE
Add in settings width limit for plugin area.

### ISSUE THREAD

**Issue by nitay-dp-ua** [projecthamster/xfce4-hamster-plugin#30]
If user like long names for activities then plugin has too big width, 50% of panel.

**Comment by nitay-dp-ua** [comment]
Thank you very much!!!

**Comment by aquaherd** [comment]
You are welcome. Could you please translate the new string, so I can release the new version?

**Comment by nitay-dp-ua** [comment]
Done
#31

**Comment by aquaherd** [comment]
Thank you.
