### ISSUE TITLE
How to build ?

### ISSUE THREAD

**Issue by brunetton** [projecthamster/xfce4-hamster-plugin#35]
Hi

Sorry for asking, but I didn't compiled a c project since my studies, a bunch of years ago ! 
Why not adding some words about how to build ?

Thanks

**Comment by aquaherd** [comment]
After git clone, cd into the directory then issue ./autogen.sh. If this works, you are ready to sudo make install.
However, you need to install the dependencies first.

**Comment by aquaherd** [comment]
Will update build instructions in readme
