### ISSUE TITLE
Update to GTK3 and XFCE 4.16

### ISSUE THREAD

**Issue by invidian** [projecthamster/xfce4-hamster-plugin#36]
Would be great to be able to run this plugin on latest version of Arch Linux.

**Comment by aquaherd** [comment]
Please check again, rebuild from scratch should work now with gtk+3 and xfce 4.16.
Thanks for bringing this to my attention.

**Comment by invidian** [comment]
I built it with modified https://aur.archlinux.org/packages/xfce4-hamster-plugin/ and it works well, thanks!

**Comment by GeraldJansen** [comment]
I tried this on current Debian testing (still xfce 4.14) and ran into problems. I had to install new build dependencies: libgtk-3-dev, libxfce4ui-2-dev and libxfce4panel-2.0-dev. I configured with `configure --prefix=local --with-icon-name=org.gnome.Hamster.GUI` and the compilation was successful. However, when trying to add the plugin to the panel, first of all the correct icon was not found and secondly I keep getting the message 'Plug-in "Hamster" unexpectedly left the panel, do you want to restart it?'. I.e. no joy.

**Comment by GeraldJansen** [comment]
@aquaherd Okay, I started over with a fresh clone and your latest commits and instructions. I only changed `hamster-applet` back to `@ICON_NAME@` in hamster.desktop.in. Now everything works fine again. Thanks!

**Comment by aquaherd** [comment]
Thank you. I will refactor icon handling since the new hamster seems to make a reappearance in Debian.
