### ISSUE TITLE
Starting again activity does does not use category of past activity

### ISSUE THREAD

**Issue by invidian** [projecthamster/xfce4-hamster-plugin#38]
It seems hitting green arrow on past activity does not copy over the category of previous activity to the new one.

**Comment by aquaherd** [comment]
I can reproduce - it is 'empty category'. 
Same with if you have 'someproject@work' and 'someproject@homeoffice'.
Will fix this.

**Comment by aquaherd** [comment]
Hi @invidian could you please review if this works for you?

**Comment by invidian** [comment]
Works as expected, thanks for figuring it out!
