### ISSUE TITLE
build issues with cmake (on debian bullseye)

### ISSUE THREAD

**Issue by GeraldJansen** [projecthamster/xfce4-hamster-plugin#47]
With a fresh clone of current master, installation fails because libhamster.so doesn't get created in the make step. Looking a bit closer, I got this:
```
[build]$ make
[ 35%] Built target translations_1
[ 35%] Built target translations
[ 45%] Built target data
[ 50%] Building C object panel-plugin/CMakeFiles/hamster.dir/button.c.o
vm.drop_caches = 3
[ 55%] Building C object panel-plugin/CMakeFiles/hamster.dir/hamster.c.o
vm.drop_caches = 3
[ 60%] Building C object panel-plugin/CMakeFiles/hamster.dir/plugin.c.o
vm.drop_caches = 3
[ 65%] Building C object panel-plugin/CMakeFiles/hamster.dir/settings.c.o
vm.drop_caches = 3
[ 70%] Building C object panel-plugin/CMakeFiles/hamster.dir/util.c.o
vm.drop_caches = 3
[ 75%] Building C object panel-plugin/CMakeFiles/hamster.dir/view.c.o
vm.drop_caches = 3
[ 80%] Building C object panel-plugin/CMakeFiles/hamster.dir/windowserver.c.o
vm.drop_caches = 3
[ 85%] Linking C shared library libhamster.so
vm.drop_caches = 3
[100%] Built target hamster
[build]$ ls panel-plugin/CMakeFiles/hamster.dir
build.make      cmake_clean.cmake  depend.internal  flags.make  progress.make
C.includecache  DependInfo.cmake   depend.make      link.txt    relink.txt
```
I'm not sure what those ` vm.drop_caches = 3` messages are about, but no object files are being created.

**Comment by aquaherd** [comment]
I need to update the instructions. The following works for me on debian bullseye:

<pre><font color="#69FF94"><b>xfce4-hamster-plugin. </b></font>cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -B build
-- Configuring done
-- Generating done
-- Build files have been written to: /home/herd/Projects/desk/xfce/xfce4-hamster-plugin/build
<font color="#69FF94"><b>xfce4-hamster-plugin. </b></font>cmake --build build
[ 36%] Built target translations_1
[ 36%] Built target translations
[ 47%] Built target data
<font color="#FF92DF"><b>Scanning dependencies of target hamster</b></font>
[ 52%] <font color="#50FA7B">Building C object panel-plugin/CMakeFiles/hamster.dir/button.c.o</font>
[ 57%] <font color="#50FA7B">Building C object panel-plugin/CMakeFiles/hamster.dir/hamster.c.o</font>
[ 63%] <font color="#50FA7B">Building C object panel-plugin/CMakeFiles/hamster.dir/plugin.c.o</font>
[ 68%] <font color="#50FA7B">Building C object panel-plugin/CMakeFiles/hamster.dir/settings.c.o</font>
[ 73%] <font color="#50FA7B">Building C object panel-plugin/CMakeFiles/hamster.dir/util.c.o</font>
[ 78%] <font color="#50FA7B">Building C object panel-plugin/CMakeFiles/hamster.dir/view.c.o</font>
[ 84%] <font color="#50FA7B">Building C object panel-plugin/CMakeFiles/hamster.dir/windowserver.c.o</font>
[ 89%] <font color="#69FF94"><b>Linking C shared library libhamster.so</b></font>
[100%] Built target hamster
<font color="#69FF94"><b>xfce4-hamster-plugin. </b></font>cmake --install build
-- Install configuration: &quot;&quot;
-- Installing: /usr/share/locale/cs/LC_MESSAGES/xfce4-hamster-plugin.mo
CMake Error at build/cmake_install.cmake:46 (file):
  file INSTALL cannot copy file
  &quot;/home/herd/Projects/desk/xfce/xfce4-hamster-plugin/build/cs.gmo&quot; to
  &quot;/usr/share/locale/cs/LC_MESSAGES/xfce4-hamster-plugin.mo&quot;: Permission
  denied.


<font color="#69FF94"><b>xfce4-hamster-plugin. </b></font>find -name hamster.so
<font color="#69FF94"><b>xfce4-hamster-plugin. </b></font>find -name libhamster.so
./build/panel-plugin/libhamster.so
<font color="#69FF94"><b>xfce4-hamster-plugin. </b></font>echo $MAKEFLAGS

<font color="#69FF94"><b>xfce4-hamster-plugin.</b></font></pre>

**Comment by aquaherd** [comment]
The fix with 17.1 is that the end install is in `/usr/lib/x86_64-linux-gnu/xfce4/panel/plugins/libhamster.so` instead of `/usr/lib/xfce4/panel/plugins/libhamster.so` hard coded but the build itself should not be affected.

**Comment by GeraldJansen** [comment]
Thanks for the feedback and new instructions. I followed them but the result is still the same (i.e. no hamster.dir/*.o files created and no libhamster.so created.) I'm still getting the messages about `vm.drop_caches = 3` and have no idea what could be triggering them.

**Comment by aquaherd** [comment]
fired up a podman and built there succeessfully - no idea how to proceed from here on

**Comment by GeraldJansen** [comment]
I must apologize for wasting your time. I had a long forgotten personal alias for `cc` as a cleancache script :-(

The build and installation works just fine now. Thanks again.

**Comment by aquaherd** [comment]
No worries.
